//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title,brand,store,price,in_stock
        ///Nike air max 2014,1,1,80,true
        ///Nike air max 2013,1,1,75.5,false
        ///Apple iPhone 5,2,1,599.99,true
        ///Apple iPhone 5,2,2,599.99,true
        ///Apple iPhone 5,2,3,549.99,true
        ///Apple iPhone 5,2,4,549.99,false
        ///Nokia Lumia 800,3,1,300,true
        ///Nokia Lumia 800,3,2,300,false
        ///Nokia Lumia 800,3,3,250,true
        ///Apple MacBook Air,2,3,999.99,true
        ///Apple MacBook Air,2,4,1099.99,true
        ///Samsung LED TV 51 inches,4,1,700,true
        ///Samsung LED TV 51 inches,4,2,900,true
        ///Samsung LED TV 51 inches,4,5,900,false
        ///Samsung Galaxy S5,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sql_engine_dataset {
            get {
                return ResourceManager.GetString("sql_engine_dataset", resourceCulture);
            }
        }
    }
}
